trigger:
  branches:
    include:
      - master
      - beta
      - production

pr:
  branches:
    include:
      - master
      - beta
      - production

variables:
  tags: 'multi-phased'
  isPR: $[ne(variables['System.PullRequest.PullRequestId'], '')]

jobs:
  - job: PreBuild
    pool: Azure-Pipelines-EO-Windows2022-Office
    displayName: 'Pre Build'
    steps:
      - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3
        displayName: 'Run Credential Scanner'
        inputs:
          debugMode: false

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-eslint.ESLint@1
        displayName: 'Run ESLint'

  - job: CommonPipeline
    dependsOn: PreBuild
    displayName: 'Common Pipeline'
    steps:
      - template: package-pipeline-template.yml
        parameters:
          PackageDirectory: 'packages/common'
          PackageName: 'common'
          SiteName: 'script-lab-react-storybook'

  - job: EditorPipeline
    dependsOn: PreBuild
    displayName: 'Editor Pipeline'
    steps:
      - template: package-pipeline-template.yml
        parameters:
          PackageDirectory: 'packages/editor'
          PackageName: 'editor'
          SiteName: 'script-lab-react'

  - job: RunnerPipeline
    dependsOn: PreBuild
    displayName: 'Runner Pipeline'
    steps:
      - template: package-pipeline-template.yml
        parameters:
          PackageDirectory: 'packages/runner'
          PackageName: 'runner'
          SiteName: 'script-lab-react-runner'

  - job: ServerPipeline
    dependsOn: PreBuild
    displayName: 'Server Pipeline'
    steps:
      - template: package-pipeline-template.yml
        parameters:
          PackageDirectory: 'packages/server'
          PackageName: 'server'
          SiteName: 'script-lab-react-server'
