trigger:
  branches:
    include:
      - master
      - beta
      - production

pr:
  branches:
    include:
      - master
      - beta
      - production

variables:
  tags: 'multi-phased'
  isPR: $[ne(variables['System.PullRequest.PullRequestId'], '')]

jobs:
  - job: Guardian
    pool:
      vmImage: 'Azure-Pipelines-EO-Windows2022-Office'
      name: Azure Pipelines
      demands:
        - npm
    displayName: 'Run Guardian'
  - job: CommonPipeline
    dependsOn: Guardian
    displayName: 'Common Pipeline'
    steps:
      - template: package-pipeline-template.yml
        parameters:
          PackageDirectory: 'packages/common'
          PackageName: 'common'
          SiteName: 'script-lab-react-storybook'

  - job: EditorPipeline
    dependsOn: Guardian
    displayName: 'Editor Pipeline'
    steps:
      - template: package-pipeline-template.yml
        parameters:
          PackageDirectory: 'packages/editor'
          PackageName: 'editor'
          SiteName: 'script-lab-react'

  - job: RunnerPipeline
    dependsOn: Guardian
    displayName: 'Runner Pipeline'
    steps:
      - template: package-pipeline-template.yml
        parameters:
          PackageDirectory: 'packages/runner'
          PackageName: 'runner'
          SiteName: 'script-lab-react-runner'

  - job: ServerPipeline
    dependsOn: Guardian
    displayName: 'Server Pipeline'
    steps:
      - template: package-pipeline-template.yml
        parameters:
          PackageDirectory: 'packages/server'
          PackageName: 'server'
          SiteName: 'script-lab-react-server'
