export declare const getCommandBarFabricTheme: (hostOrTheme: string | ITheme) => import("@uifabric/styling/lib/interfaces/ITheme").ITheme;
export declare const getTheme: (host: string) => ITheme;
export declare const fabricTheme: {
    themePrimary: string;
    themeLighterAlt: string;
    themeLighter: string;
    themeLight: string;
    themeTertiary: string;
    themeSecondary: string;
    themeDarkAlt: string;
    themeDark: string;
    themeDarker: string;
    neutralLighterAlt: string;
    neutralLighter: string;
    neutralLight: string;
    neutralQuaternaryAlt: string;
    neutralQuaternary: string;
    neutralTertiaryAlt: string;
    neutralTertiary: string;
    neutralSecondary: string;
    neutralPrimaryAlt: string;
    neutralPrimary: string;
    neutralDark: string;
    black: string;
    white: string;
    primaryBackground: string;
    primaryText: string;
    bodyBackground: string;
    bodyText: string;
    disabledBackground: string;
    disabledText: string;
};
export declare const setupFabricTheme: (host: string) => void;
